package datos;
// Generated 11 ene 2024 12:21:02 by Hibernate Tools 6.0.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private int id;
	private String descripcion;
	private Integer stockactual;
	private Integer stockminimo;
	private Float precio;
	private Set ventas = new HashSet(0);

	public Producto() {
	}

	public Producto(int id) {
		this.id = id;
	}

	public Producto(int id, String descripcion, Integer stockactual, Integer stockminimo, Float precio, Set ventas) {
		this.id = id;
		this.descripcion = descripcion;
		this.stockactual = stockactual;
		this.stockminimo = stockminimo;
		this.precio = precio;
		this.ventas = ventas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getStockactual() {
		return this.stockactual;
	}

	public void setStockactual(Integer stockactual) {
		this.stockactual = stockactual;
	}

	public Integer getStockminimo() {
		return this.stockminimo;
	}

	public void setStockminimo(Integer stockminimo) {
		this.stockminimo = stockminimo;
	}

	public Float getPrecio() {
		return this.precio;
	}

	public void setPrecio(Float precio) {
		this.precio = precio;
	}

	public Set getVentas() {
		return this.ventas;
	}

	public void setVentas(Set ventas) {
		this.ventas = ventas;
	}

}
