package datos;
// Generated 14 dic 2023 10:23:04 by Hibernate Tools 6.3.1.Final

import java.sql.Date;

/**
 * Prestamo generated by hbm2java
 */
public class Prestamo implements java.io.Serializable {

	private PrestamoId id;
	private Libro libro;
	private Socio socio;
	private Date finio;
	private Date ffin;

	public Prestamo() {
	}

	public Prestamo(PrestamoId id, Libro libro, Socio socio, Date finio, Date ffin) {
		this.id = id;
		this.libro = libro;
		this.socio = socio;
		this.finio = finio;
		this.ffin = ffin;
	}

	public PrestamoId getId() {
		return this.id;
	}

	public void setId(PrestamoId id) {
		this.id = id;
	}

	public Libro getLibro() {
		return this.libro;
	}

	public void setLibro(Libro libro) {
		this.libro = libro;
	}

	public Socio getSocio() {
		return this.socio;
	}

	public void setSocio(Socio socio) {
		this.socio = socio;
	}

	public Date getFinio() {
		return this.finio;
	}

	public void setFinio(Date finio) {
		this.finio = finio;
	}

	public Date getFfin() {
		return this.ffin;
	}

	public void setFfin(Date ffin) {
		this.ffin = ffin;
	}

}
