package datos;
// Generated 14 dic 2023 10:23:04 by Hibernate Tools 6.3.1.Final

/**
 * PrestamoId generated by hbm2java
 */
public class PrestamoId implements java.io.Serializable {

	private int clibro;
	private int csocio;

	public PrestamoId() {
	}

	public PrestamoId(int clibro, int csocio) {
		this.clibro = clibro;
		this.csocio = csocio;
	}

	public int getClibro() {
		return this.clibro;
	}

	public void setClibro(int clibro) {
		this.clibro = clibro;
	}

	public int getCsocio() {
		return this.csocio;
	}

	public void setCsocio(int csocio) {
		this.csocio = csocio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrestamoId))
			return false;
		PrestamoId castOther = (PrestamoId) other;

		return (this.getClibro() == castOther.getClibro()) && (this.getCsocio() == castOther.getCsocio());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getClibro();
		result = 37 * result + this.getCsocio();
		return result;
	}

}
